plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.rometools:rome:2.1.0'
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'com.google.code.gson:gson:2.10.1'
}

application {
    mainClass = 'bot.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'bot.Main'
    }
}
